spring:
  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: ${GEMINI_API_KEY:}
        chat:
          options:
            model: gemini-2.5-flash

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY:}
      model-name: gemini-2.5-flash
