spring:
  ai:
    model:
      chat: google-genai
      audio:
        speech: none
        transcription: none
      embedding: none
      image: none
      moderation: none
    google:
      genai:
        api-key: ${GEMINI_API_KEY:}
        chat:
          options:
            model: gemini-2.5-flash

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY:}
      model-name: gemini-3.6-flash
    streaming-chat-model:
      api-key: ${GEMINI_API_KEY:}
      model-name: gemini-3.6-flash
      return-thinking: true
      send-thinking: true
    embedding-model:
      api-key: ${GEMINI_API_KEY:}
      model-name: gemini-embedding-2-preview
